trigger:
- main

jobs:
- job: TestACR
  timeoutInMinutes: 360

  pool:
    vmImage: ubuntu-18.04

  steps:
  - task: Docker@2
    displayName: login
    inputs:
      containerRegistry: cusacrtest
      command: login

  - bash: ls /data/instancename

  - bash: chmod +x pull.sh && ./pull.sh

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: './cus.pcap'
      artifactName: pcap
