trigger:
- main

schedules:
- cron: "*/30 * * * *"
  displayName: run 15-minutes test every 30 minutes
  branches:
    include:
    - main
  always: true

pool:
  vmImage: ubuntu-18.04

steps:
- task: Docker@2
  displayName: login
  inputs:
    containerRegistry: eusacrtest
    command: login

- bash: chmod +x pull.sh && ./pull.sh
