trigger:
- main

pool:
  vmImage: ubuntu-18.04

schedules:
- cron: "1 */4 * * *"
  displayName: run once in 4 hours
  branches:
    include:
    - main
  always: true

steps:
- task: Docker@2
  displayName: login
  inputs:
    containerRegistry: cusacrtest
    command: login

- bash: ls /data/instancename

- bash: chmod +x pull.sh && ./pull.sh
  timeoutInMinutes: 360

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: './cus.pcap'
    artifactName: pcap
