name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  my_job:
    runs-on: windows-2019
    steps:
      - name: test .net list
        run: | 
          ls "C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk\"