name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  my_job:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: give it a try
        run: | 
          sudo apt-get update -y
          sudo apt-get -y install libsodium23 libsodium-dev
          sudo apt-get -y install libsystemd0 libsystemd-dev
          sudo apt-get -y remove --purge software-properties-common
          sudo apt-get -y autoremove