name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  my_job:
    runs-on: windows-2019
    steps:
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.201
      - name: test .net list
        run: | 
          ls "C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk\3.1.201\Sdks\Microsoft.NET.Sdk\"
      - name: test .net list
        run: | 
          ls "C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk\3.1.201\Sdks\Microsoft.NET.Sdk\Sdk\"
      - name: test .net list
        run: | 
          ls "C:\Users\runneradmin\AppData\Local\Microsoft\dotnet\sdk\3.1.201\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.NuGet.targets"