name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: windows-latest
    steps:
      - run: netstat -an
      - run: Get-ChildItem c:\\data\\instancename
      - run: get-service