name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    env:
      scriptPath: "source/BuildScripts"
      WORKSPACE: ${{ github.workspace }}
    runs-on: windows-latest
    steps:

    - name: Set variables
      run: | 
        echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Set card variables
      run: | 
        echo 'FULL_URL=$("http://bla-auto-"$BRANCH".gg.gg/")' >> $GITHUB_ENV

    - name: Set card variables
      run: | 
        echo $FULL_URL