name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    env:
      scriptPath: "source/BuildScripts"
      WORKSPACE: ${{ github.workspace }}
    runs-on: windows-latest
    steps:

      - run: echo ${{ github.workspace }}
      - run: echo $env:WORKSPACE