name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - run: echo $BRANCH