name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  my_job:
    runs-on:  ubuntu-18.04
    steps:
      - name: gh host ip address
        run: | 
          dig +short myip.opendns.com @resolver1.opendns.com
      - uses: azure/docker-login@v1
        with:
          login-server: eusacrtest.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: get rabbitmq image
        run: | 
          docker pull eusacrtest.azurecr.io/rabbitmqtest