name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    env:
      scriptPath: "source/BuildScripts"
      WORKSPACE: ${{ github.workspace }}
    runs-on: ubuntu-latest
    steps:

    - name: Set variables
      run: | 
        echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Set card variables
      run: | 
        echo 'FULL_URL="http://bla-auto-"${GITHUB_REF##*/}".gg.gg/"' >> $GITHUB_ENV

    - name: Set card variables
      run: | 
        echo ${{ env.FULL_URL }}