name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  env:
    scriptPath: "source/BuildScripts"
  tests:
    runs-on: ubuntu-latest
    steps:

      - name: cdktf older version
        run: echo $scriptPath