name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  my_job:
    runs-on:  windows-latest
    steps:
      - name: test user priviledges
        run: | 
          whoami /groups