name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "DB_VM_INTERNAL_IP=$(hostname)" >> $GITHUB_ENV
      - run: echo $DB_VM_INTERNAL_IP