name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: | 
          sudo chmod 777 /usr/local/lib/node_modules -R && sudo chmod 777 /usr/local/bin
      - run: npm install -g pnpm
      - run: pnpm --version