name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    env:
      scriptPath: "source/BuildScripts"
    runs-on: windows-latest
    steps:

      - run: echo ${{ github.job }}
      - run: echo ${{ github.run_id }}
      - run: echo ${{ github.run_number }}
      - run: echo ${{ github.run_attempt }}