name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    env:
      scriptPath: "source/BuildScripts"
    runs-on: ubuntu-latest
    steps:

      - name: cdktf older version
        run: echo $env:scriptPath